### ISSUE TITLE
upgrade_mode = "Manual" doesnot work properly

### ISSUE THREAD

**Issue by jzheng2022** [PaloAltoNetworks/terraform-azurerm-vmseries-modules#256] opened 2023-04-21 18:45 UTC
### Describe the bug

With upgrade_mode = "Manual", if the image id changed, the firewall scale set instance will re-launch randomly. This is caused by (ref https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/features-block#virtual_machine_scale_set) :
virtual_machine_scale_set {
      ...
      roll_instances_when_required  = true
      ...
    }
This need to be fixed in the code if upgrade_mode = "Manual" is hard coded.

### Module Version

v0.5.5

### Expected behavior

When change the image id, the vm scale set instance should just shows it is not running the latest version, and not to re-launch the instance.

**Comment by migara** [comment] 2023-05-24 10:55
Duplicate of https://github.com/PaloAltoNetworks/terraform-azurerm-vmseries-modules/issues/253

**Comment by FoSix** [comment] 2023-05-25 12:54
@jzheng2022 this provider feature `roll_instances_when_required = true` is actually already introduced, but in the [example code](https://github.com/PaloAltoNetworks/terraform-azurerm-vmseries-modules/blob/main/examples/dedicated_vmseries_and_autoscale/versions.tf#L24), not in the module. 

Testing if this can be moved to provider configuration in the module.

**Comment by FoSix** [comment] 2023-05-25 13:09
unfortunately the module cannot have it's own provider block:

![image](https://github.com/PaloAltoNetworks/terraform-azurerm-vmseries-modules/assets/42772730/bf2db726-10d5-4fad-8f08-7c7494c3e577)

**Comment by FoSix** [comment] 2023-05-25 13:43
added documentation in #265

**Closed** 2023-05-31 10:15 UTC
